Repository dnd-side-project/dnd-11th-2-backend, pull requests merged in 2024-07, with the labels that each got.

#6 Chore: spotless 플러그인 추가
  .github/workflows/CI.yml
  build.gradle.kts
  scripts/pre-commit.sh
  src/test/java/com/dnd/runus/RunUsApplicationTests.java
Labels: chore

#7 Chore: Springboot web, jpa, lombok 의존성 추가
  .gitignore
  build.gradle.kts
  src/main/resources/.env.example
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: chore

#9 Feat: Swagger 설정 추가
  build.gradle.kts
  src/main/java/com/dnd/runus/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: documentation, chore

#12 Feat: member 엔티티 추가
  build.gradle.kts
  src/main/java/com/dnd/runus/domain/common/BaseTimeEntity.java
  src/main/java/com/dnd/runus/domain/member/entity/Member.java
  src/main/java/com/dnd/runus/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/runus/global/config/JpaConfig.java
  src/main/java/com/dnd/runus/global/constant/MemberRole.java
  src/main/java/com/dnd/runus/global/constant/SocialType.java
Labels: feature

#13 Fix: imageName에서 version을 가져오도록 수정
  build.gradle.kts
Labels: chore

#18 Fix: windows 환경에서도 포메팅 스크립트가 실행하도록 수정
  build.gradle.kts
  scripts/pre-commit.sh
Labels: bug

#17 Feat: API 공통 핸들러 추가
  src/main/java/com/dnd/runus/global/config/SwaggerConfig.java
  src/main/java/com/dnd/runus/global/exception/BaseException.java
  src/main/java/com/dnd/runus/global/exception/BusinessException.java
  src/main/java/com/dnd/runus/global/exception/NotFoundException.java
  src/main/java/com/dnd/runus/global/exception/type/ApiErrorType.java
  src/main/java/com/dnd/runus/global/exception/type/ErrorType.java
  src/main/java/com/dnd/runus/presentation/config/ObjectMapperConfig.java
  src/main/java/com/dnd/runus/presentation/config/WebConfig.java
  src/main/java/com/dnd/runus/presentation/dto/response/ApiErrorDto.java
  src/main/java/com/dnd/runus/presentation/dto/response/ApiResponse.java
  src/main/java/com/dnd/runus/presentation/handler/ApiResponseHandler.java
  src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java
  src/main/java/com/dnd/runus/presentation/handler/NullResponseHandler.java
Labels: documentation, feature

#21 Feat: security 의존성 추가, cors 설정
  build.gradle.kts
  src/main/java/com/dnd/runus/auth/exception/AuthException.java
  src/main/java/com/dnd/runus/global/config/SwaggerConfig.java
  src/main/java/com/dnd/runus/global/constant/AuthConstant.java
  src/main/java/com/dnd/runus/global/exception/type/ErrorType.java
  src/main/java/com/dnd/runus/presentation/config/SecurityFilterConfig.java
  src/main/java/com/dnd/runus/presentation/config/SecurityHttpConfigurer.java
  src/main/java/com/dnd/runus/presentation/config/SecurityWebConfig.java
  src/main/java/com/dnd/runus/presentation/filter/AuthenticationCheckFilter.java
  src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java
  src/main/java/com/dnd/runus/presentation/handler/UnauthorizedHandler.java
  src/main/resources/.env.example
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: feature, chore

#23 Feat: jwt token 발급, 검증 필터 추가
  build.gradle.kts
  src/main/java/com/dnd/runus/auth/config/TokenConfig.java
  src/main/java/com/dnd/runus/auth/token/TokenProviderModule.java
  src/main/java/com/dnd/runus/auth/token/access/AccessTokenProvider.java
  src/main/java/com/dnd/runus/auth/token/dto/AuthTokenClaimDto.java
  src/main/java/com/dnd/runus/auth/token/dto/AuthTokenDto.java
  src/main/java/com/dnd/runus/auth/token/strategry/JwtTokenStrategy.java
  src/main/java/com/dnd/runus/auth/token/strategry/TokenStrategy.java
  src/main/java/com/dnd/runus/auth/userdetails/AuthUserDetails.java
  src/main/java/com/dnd/runus/auth/userdetails/UserDetailsServiceImpl.java
  src/main/java/com/dnd/runus/presentation/config/SecurityFilterConfig.java
  src/main/java/com/dnd/runus/presentation/filter/AuthenticationCheckFilter.java
  src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java
  src/main/resources/.env.example
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: feature, chore

#24 Feat: member profile, badge 엔티티 추가
  src/main/java/com/dnd/runus/domain/badge/entity/Badge.java
  src/main/java/com/dnd/runus/domain/badge/entity/BadgeAchievement.java
  src/main/java/com/dnd/runus/domain/level/entity/Level.java
  src/main/java/com/dnd/runus/domain/member/entity/Member.java
  src/main/java/com/dnd/runus/domain/member/entity/PersonalProfile.java
  src/main/java/com/dnd/runus/domain/member/entity/SocialProfile.java
  src/main/java/com/dnd/runus/global/constant/BadgeType.java
Labels: feature

#22 Feat: PostGIS 의존성 추가, 러닝 엔티티 추가
  build.gradle.kts
  src/main/java/com/dnd/runus/domain/runing/entity/RunningEmoji.java
  src/main/java/com/dnd/runus/domain/runing/entity/RunningRecord.java
  src/main/java/com/dnd/runus/domain/runing/repository/RunningEmojiRepository.java
  src/main/java/com/dnd/runus/domain/runing/repository/RunningRecordRepository.java
  src/main/resources/application.yml
Labels: feature, chore

#27 Feat: time format 설정
  src/main/java/com/dnd/runus/domain/example/ExampleController.java
  src/main/java/com/dnd/runus/global/config/SwaggerConfig.java
  src/main/java/com/dnd/runus/global/constant/TimeConstant.java
  src/main/java/com/dnd/runus/presentation/config/ObjectMapperConfig.java
Labels: documentation, feature
