Repository dnd-side-project/dnd-11th-2-backend, pull requests merged in 2024-10, with the labels that each got.

#248 Feat: 나의 뱃지 목록 조회 리파지토리 구현
  src/main/java/com/dnd/runus/domain/badge/Badge.java
  src/main/java/com/dnd/runus/domain/badge/BadgeRepository.java
  src/main/java/com/dnd/runus/domain/badge/BadgeWithAchieveStatusAndAchievedAt.java
  src/main/java/com/dnd/runus/global/constant/BadgeType.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeEntity.java
  src/test/java/com/dnd/runus/application/badge/BadgeServiceTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeRepositoryTest.java
Labels: feature

#250 Feat: 나의 뱃지 목록 조회 api 구현
  src/main/java/com/dnd/runus/application/badge/BadgeService.java
  src/main/java/com/dnd/runus/presentation/v1/badge/BadgeController.java
  src/main/java/com/dnd/runus/presentation/v1/badge/dto/response/AllBadgesListResponse.java
  src/test/java/com/dnd/runus/application/badge/BadgeServiceTest.java
Labels: feature

#252 Feat: 밤 버전 날씨 아이콘 추가
  src/main/java/com/dnd/runus/global/constant/WeatherType.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherInfo.java
  src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/WeatherApiComWeatherClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/dto/WeatherapicomCurrent.java
  src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
Labels: feature

#254 Fix: OpenweathermapWeatherClient 예보 정보를 받아와 일일 최고 최저 기온를 반환하도록 수정
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherInfo.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/dto/OpenweathermapCurrent.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/dto/OpenweathermapForecast.java
  src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClientTest.java
  src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
Labels: bug

#256 Fix: 0초인 Pace를 파싱이나 직렬화 할 때 0 대신 -를 사용하도록 수정
  src/main/java/com/dnd/runus/domain/common/Pace.java
  src/test/java/com/dnd/runus/domain/common/PaceTest.java
Labels: bug

#259 Fix: 평균페이스를 서버에서 계산하도록 수정
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/domain/common/Pace.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/RunningRecordMetricsForAddDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordRequest.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: bug, feature

#263 Fix: 활동요약 응답 형식 변경
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/WeeklyRunningRatingDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordWeeklySummaryResponse.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: feature

#271 Docs: readme 앱스토어 배포 링크 추가
  README.md
Labels: documentation

#277 Fix: 뱃지 리스트 조회 API 응답형식 변경
  src/main/java/com/dnd/runus/application/badge/BadgeService.java
  src/main/java/com/dnd/runus/domain/badge/BadgeWithAchieveStatusAndAchievedAt.java
  src/main/java/com/dnd/runus/presentation/v1/badge/dto/response/AllBadgesListResponse.java
  src/test/java/com/dnd/runus/application/badge/BadgeServiceTest.java
Labels: feature

#278 Fix: 날짜가 바뀌면 새로운 날짜 파일에 log를 기록하도록 수정
  src/main/resources/logback-spring.xml
Labels: bug

#276 Refactor: OauthService 회원 가입, 로그인, 탈퇴 시 Oauth id token, access token 요청/응답과 db 트랜잭션 분리
  src/main/java/com/dnd/runus/application/member/MemberEventHandler.java
  src/main/java/com/dnd/runus/application/member/MemberService.java
  src/main/java/com/dnd/runus/application/member/MemberWithdrawService.java
  src/main/java/com/dnd/runus/application/member/event/SignupEvent.java
  src/main/java/com/dnd/runus/application/member/event/WithdrawEvent.java
  src/main/java/com/dnd/runus/application/oauth/OauthService.java
  src/main/java/com/dnd/runus/application/oauth/SocialProfileService.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/JpaSocialProfileRepository.java
  src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
Labels: refactor

#280 Fix: badge_achievement 테이블에 unique key 추가
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeAchievementEntity.java
  src/main/resources/db/migration/V5.0.13__badge_achievement_unique.sql
Labels: bug

#283 Feat: badge_achievement 중복 무시하고 저장하는 함수 추가
  src/main/java/com/dnd/runus/domain/badge/BadgeAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeAchievementRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImplTest.java
Labels: feature

#286 Feat: 회원가입 뱃지 부여 기능 추가
  src/main/java/com/dnd/runus/application/badge/BadgeEventHandler.java
  src/main/java/com/dnd/runus/application/badge/BadgeService.java
  src/main/java/com/dnd/runus/domain/badge/BadgeRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/JpaBadgeRepository.java
Labels: feature

#287 Fix: 활동요약에서 저번주 평균값이 이번주 평균값으로 나오는 버그 수정
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: bug

#291 Feat: RunningRecordAddedEvent 이벤트를 수신하여 러닝 뱃지 부여 로직 추가
  src/main/java/com/dnd/runus/application/badge/BadgeEventHandler.java
  src/main/java/com/dnd/runus/application/member/MemberEventHandler.java
  src/main/java/com/dnd/runus/application/member/MemberService.java
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/application/running/event/RunningRecordAddedEvent.java
  src/main/java/com/dnd/runus/application/scale/ScaleEventHandler.java
  src/main/java/com/dnd/runus/application/scale/ScaleService.java
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: feature
