Repository dnd-side-project/dnd-11th-2-backend, pull requests merged in 2024-09, with the labels that each got.

#119 Fix: MockWeatherClient 삭제
  src/main/java/com/dnd/runus/infrastructure/weather/mock/MockWeatherClient.java
  src/main/resources/.env.example
Labels: bug

#122 Fix: weather openweathermap api 요청시 request param에 appid를 포함하도록 수정
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java
  src/main/java/com/dnd/runus/presentation/v1/weather/WeatherController.java
  src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
Labels: bug

#123 Fix: 인식하지 못하는 ZoneOffset 대신 defaultZoneOffset을 사용하도록 수정
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
Labels: bug

#126 Docs: running record api docs 필드 example 추가
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlyDatesResponse.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSummaryResponse.java
Labels: documentation

#125 Fix: 기존의 임시 weather 문구를 정해진 문장으로 수정
  src/main/java/com/dnd/runus/global/constant/WeatherType.java
Labels: feature

#129 Fix: openweathermap api 요청시 단위를 켈빈온도에서 섭씨온도로 변경
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientConfig.java
  src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
Labels: bug

#130 Feat: scale index 순서 컬럼 추가
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/Scale.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java
  src/main/resources/db/migration/V5.0.8__scale_index.sql
Labels: feature

#131 Fix: 잘못된 ZoneOffset 대신 defaultZoneOffset을 사용하도록 수정
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
Labels: bug

#133 Fix: RunningService.getRunningRecordSummaries 메서드에 readOnly 트랜잭션 추가
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
Labels: bug

#134 Feat: scale table에 start_name, end_name 컬럼 추가
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/Scale.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java
  src/main/resources/db/migration/V5.0.9__add_scale_from_to_column.sql
Labels: feature

#136 Feat: running record 저장시 사용자 목표 성취 저장 함수를 RunningRecordService에 추가
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: feature

#138 Feat: 지구 한 바퀴 코스 서머리 조회
  src/main/java/com/dnd/runus/application/scale/ScaleService.java
  src/main/java/com/dnd/runus/domain/scale/Scale.java
  src/main/java/com/dnd/runus/domain/scale/ScaleRepository.java
  src/main/java/com/dnd/runus/domain/scale/ScaleSummary.java
  src/main/java/com/dnd/runus/global/constant/ScaleConstant.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/Scale.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java
  src/main/java/com/dnd/runus/presentation/v1/scale/ScaleController.java
  src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleSummaryResponse.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
Labels: feature

#139 Feat: 지구 한 바퀴 사용자 성취 테이블, 엔티티, 도메인 생성
  src/main/java/com/dnd/runus/domain/scale/ScaleAchievement.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleAchievementEntity.java
  src/main/resources/db/migration/V5.0.10__create_scale_achievement_table.sql
Labels: feature

#143 Fix: 지구 한 바퀴 성취 엔티티 member, scale의 연관 관계 수정
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleAchievementEntity.java
  src/main/resources/db/migration/V5.0.11__remove_uk_alter_scale_achievement_table.sql
Labels: feature

#144 Feat: app version 확인 API 추가
  src/main/java/com/dnd/runus/presentation/v1/server/ServerController.java
  src/main/java/com/dnd/runus/presentation/v1/server/dto/response/VersionStatusResponse.java
Labels: feature

#148 Fix: route에 임시 좌표로 running_record를 저장하도록 수정
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: bug

#150 Fix: scale 테이블에 달성 목표 값을 나타내는 achievement_value_meter컬럼 추가
  src/main/java/com/dnd/runus/domain/scale/Scale.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java
  src/main/resources/db/migration/V5.0.12__add_scale_from_to_column.sql
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
Labels: feature

#155 Feat: scale 기록 조회 함수를 ScaleAchievementRepository에 추가
  src/main/java/com/dnd/runus/domain/scale/ScaleAchievementLog.java
  src/main/java/com/dnd/runus/domain/scale/ScaleAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleAchievementEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntityTest.java
Labels: feature

#156 Feat: scale 코스 목록 조회 API 추가
  src/main/java/com/dnd/runus/application/scale/ScaleService.java
  src/main/java/com/dnd/runus/presentation/v1/scale/ScaleController.java
  src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java
  src/test/java/com/dnd/runus/application/scale/ScaleServiceTest.java
Labels: feature

#157 Feat: 저장할 수 있는 scale_id 리스트 조회 repository
  src/main/java/com/dnd/runus/domain/scale/ScaleRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
Labels: feature

#158 Feat: ScaleAchievement 저장 함수 리파지토리 추가
  src/main/java/com/dnd/runus/domain/scale/Scale.java
  src/main/java/com/dnd/runus/domain/scale/ScaleAchievement.java
  src/main/java/com/dnd/runus/domain/scale/ScaleAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/JpaScaleAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleAchievementEntity.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryTest.java
Labels: feature

#160 Fix: 챌린지 성취 퍼센테이지 저장 버그 수정
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeWithCondition.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeAchievementEntity.java
Labels: bug

#161 Feat: 러닝 저장 시 사용자 ScaleAchievement 저장 로직 추가
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleRepository.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
Labels: feature

#165 Fix : 컴파일 시 발생하는 unknown enum constant When.MAYBE 경고 제거
  build.gradle.kts
  gradle/libs.versions.toml
Labels: bug

#166 Docs: readme 내용 추가
  README.md
Labels: documentation

#168 Feat: 회원 탈퇴를 위한 챌린지 성취 퍼센테이지 삭제 메서드 구현
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementPercentageRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeAchievementPercentageRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java
Labels: feature

#169 Feat: 회원 탈퇴를 위한 GoalAchievementRepository 삭제 메서드 구현
  src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/goalAchievement/GoalAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/goalAchievement/JpaGoalAchievementRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/goalAchievement/GoalAchievementRepositoryImplTest.java
Labels: feature

#171 Feat: 회원 탈퇴를 위한 멤버 아이디로 러닝 데이터 찾는 메서드 구현
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/JpaRunningRecordRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
Labels: feature

#170 Feat: 회원 탈퇴를 위한 ScaleAchievementRepository에 삭제 메서드 구현
  src/main/java/com/dnd/runus/domain/scale/ScaleAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/JpaScaleAchievementRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImplTest.java
Labels: feature

#167 Feat: 회원 탈퇴를 위한 ChallengeAchievementRepository에 관련 메서드 구현
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeAchievementRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
Labels: feature

#179 Refactor: 회원탈퇴 로직 리팩터링(hard delete)
  src/main/java/com/dnd/runus/application/oauth/OauthService.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java
  src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImplTest.java
Labels: refactoring

#187 Feat: running record 저장 시 goal 성공과 미달 이미지 추가
  src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievement.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/GoalResultDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
Labels: feature

#182 Feat: 주간, 요일별 러닝 거리 데이터 조회 리파지토리 함수 추가
  src/main/java/com/dnd/runus/domain/running/DailyRunningRecordSummary.java
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
Labels: feature

#189 Feat: 일별 달린 시간을 조회하는 함수 리파지토리에 추가
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
Labels: feature

#191 Feat: 활동 요약 조회 API
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/global/constant/MetricsConversionFactor.java
  src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordWeeklySummaryType.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordWeeklySummaryResponse.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: feature

#203 Fix: openweathermap api 요청 시 unit을 units로 오타 수정
  src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java
  src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
Labels: bug

#206 Fix: daily 러닝 기록 조회 api 문서 오류 수정
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSummaryResponse.java
  src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java
Labels: documentation

#224 Chore: java 17에서 21로 버전 마이그레이션
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore

#227 Refactor: OauthService.revokeOauth 메서드에서 revoke 호출을 가상 스레드를 이용한 비동기 호출로 변경
  src/main/java/com/dnd/runus/application/oauth/OauthService.java
  src/main/java/com/dnd/runus/auth/oidc/client/RestClientConfig.java
  src/main/java/com/dnd/runus/auth/oidc/provider/apple/AppleOidcProvider.java
  src/main/java/com/dnd/runus/global/exception/type/ErrorType.java
  src/main/resources/application.yml
  src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
  src/test/resources/application.yml
Labels: refactoring

#226 Feat: running record id로 러닝 기록 조회 api 추가
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordQueryResponse.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: feature

#233 Fix: running record 조회 api에서 잘못된 uri 매핑 수정
  src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
Labels: bug

#235 Feat: Blue-Green 배포 구현
  .github/workflows/CD.yml
Labels: feature

#232 Feat: virtual thread 사용한 AsyncConfig 추가
  src/main/java/com/dnd/runus/application/config/AsyncConfig.java
Labels: feature

#231 Feat: TransactionEventHandler 클래스 추가
  src/main/java/com/dnd/runus/application/config/TransactionEventHandler.java
  src/main/java/com/dnd/runus/global/event/AfterTransactionEvent.java
  src/main/java/com/dnd/runus/global/event/BeforeTransactionEvent.java
  src/main/java/com/dnd/runus/global/event/TransactionEvent.java
Labels: feature

#245 Refactor: OauthService.deleteAllDataAboutMember 메서드를 MemberWithdrawService 클래스로 분리
  src/main/java/com/dnd/runus/application/member/MemberWithdrawService.java
  src/main/java/com/dnd/runus/application/oauth/OauthService.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java
  src/test/java/com/dnd/runus/application/member/MemberWithdrawServiceTest.java
  src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
Labels: refactoring
