Repository dnd-side-project/dnd-11th-2-backend, pull requests merged in 2024-08, with the labels that each got.

#25 설계한 ERD롤 토대로 JPA 엔티티 클래스들을 추가
  build.gradle.kts
  src/main/java/com/dnd/runus/domain/badge/entity/Badge.java
  src/main/java/com/dnd/runus/domain/badge/entity/BadgeAchievement.java
  src/main/java/com/dnd/runus/domain/level/entity/Level.java
  src/main/java/com/dnd/runus/domain/member/entity/Member.java
  src/main/java/com/dnd/runus/domain/member/entity/MemberLevel.java
  src/main/java/com/dnd/runus/domain/member/entity/PersonalProfile.java
  src/main/java/com/dnd/runus/domain/member/entity/SocialProfile.java
  src/main/java/com/dnd/runus/domain/runing/entity/RunningEmoji.java
  src/main/java/com/dnd/runus/domain/runing/entity/RunningRecord.java
  src/main/java/com/dnd/runus/domain/runing/repository/RunningEmojiRepository.java
  src/main/java/com/dnd/runus/domain/runing/repository/RunningRecordRepository.java
  src/main/java/com/dnd/runus/global/constant/BadgeType.java
  src/main/resources/application.yml
Labels: feature

#42 Feat: flyway 적용
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/com/dnd/runus/domain/level/Level.java
  src/main/java/com/dnd/runus/domain/member/Member.java
  src/main/java/com/dnd/runus/domain/member/MemberLevel.java
  src/main/java/com/dnd/runus/domain/member/SocialProfile.java
  src/main/java/com/dnd/runus/domain/oauth/service/OauthService.java
  src/main/java/com/dnd/runus/domain/running/RunningEmoji.java
  src/main/java/com/dnd/runus/domain/running/RunningRecord.java
  src/main/java/com/dnd/runus/global/constant/RunningEmoji.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/SocialProfileRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberLevelEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/SocialProfileEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/JpaRunningEmojiRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningEmojiEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__create_tables.sql
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberEntityTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntityTest.java
  src/test/resources/application.yml
Labels: feature, chore

#44 Fix: ddl-auto validate 속성으로 변경
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeAchievementEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: chore

#51 Feat: 러닝 기록 멤버id로 삭제 구현
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/JpaRunningRecordRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
Labels: feature

#55 Feat: 회원탈퇴 구현
  .gitignore
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/com/dnd/runus/application/oauth/OauthService.java
  src/main/java/com/dnd/runus/auth/oidc/provider/OidcProvider.java
  src/main/java/com/dnd/runus/auth/oidc/provider/OidcProviderFactory.java
  src/main/java/com/dnd/runus/auth/oidc/provider/impl/AppleAuthProvider.java
  src/main/java/com/dnd/runus/client/vo/AppleAuthRevokeRequest.java
  src/main/java/com/dnd/runus/client/vo/AppleAuthTokenRequest.java
  src/main/java/com/dnd/runus/client/vo/AppleAuthTokenResponse.java
  src/main/java/com/dnd/runus/client/web/AppleAuthClient.java
  src/main/java/com/dnd/runus/client/web/AppleAuthClientComponent.java
  src/main/java/com/dnd/runus/domain/badge/BadgeAchievement.java
  src/main/java/com/dnd/runus/domain/badge/BadgeAchievementRepository.java
  src/main/java/com/dnd/runus/domain/member/MemberLevelRepository.java
  src/main/java/com/dnd/runus/domain/member/MemberRepository.java
  src/main/java/com/dnd/runus/domain/member/SocialProfileRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/SocialProfileRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/JpaBadgeAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/JpaMemberLevelRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/JpaSocialProfileRepository.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/dto/request/OauthRequest.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/dto/request/WithdrawRequest.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/dto/response/TokenResponse.java
  src/main/resources/.env.example
  src/main/resources/application.yml
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/SocialProfileRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
  src/test/resources/application.yml
Labels: feature, chore

#52 Feat: RunningRecord controller record 추가 api 추가
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/global/constant/RunningEmoji.java
  src/main/java/com/dnd/runus/global/exception/type/ErrorType.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/ChallengeDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/RunningRecordMetricsDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordRequest.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordReportResponse.java
  src/main/resources/application.yml
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
  src/test/resources/application.yml
Labels: feature

#62 Chore: jOOQ 의존성 설정
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/java/com/dnd/runus/global/config/JooqConfig.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/member/MemberJooqRepository.java
  src/test/java/com/dnd/runus/config/TestJooqConfig.java
  src/test/java/com/dnd/runus/infrastructure/persistence/annotation/RepositoryTest.java
Labels: feature, chore

#64 Fix: docker compose에서 Class Path 디렉토리로 마운팅할 수 없는 오류 수정
  .gitignore
  src/main/java/com/dnd/runus/auth/oidc/provider/impl/AppleAuthProvider.java
  src/main/resources/app/apple/.gitkeep
Labels: bug, chore

#67 Feat: member 레벨업 기능 추가
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/domain/level/LevelRepository.java
  src/main/java/com/dnd/runus/domain/member/MemberLevel.java
  src/main/java/com/dnd/runus/domain/member/MemberLevelRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/level/LevelRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/member/JooqMemberLevelRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/level/JpaLevelRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/level/entity/LevelEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/JpaMemberLevelRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberLevelEntity.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
  src/test/java/com/dnd/runus/config/TestJooqConfig.java
  src/test/java/com/dnd/runus/infrastructure/persistence/annotation/RepositoryTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImplTest.java
Labels: feature

#73 Docs: 회원 탈퇴 api 문서
  src/main/java/com/dnd/runus/application/oauth/OauthService.java
  src/main/java/com/dnd/runus/auth/oidc/provider/OidcProvider.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/dto/request/WithdrawRequest.java
Labels: documentation

#69 Feat: 오늘의 챌린지 조회 기능 구현
  src/main/java/com/dnd/runus/application/challenge/ChallengeService.java
  src/main/java/com/dnd/runus/domain/challenge/Challenge.java
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/global/constant/ChallengeGoalType.java
  src/main/java/com/dnd/runus/global/constant/ChallengeType.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeData.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/JpaRunningRecordRepository.java
  src/main/java/com/dnd/runus/presentation/v1/challenge/ChallengeController.java
  src/main/java/com/dnd/runus/presentation/v1/challenge/dto/response/ChallengesResponse.java
  src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
Labels: feature

#76 Feat: level image_url 컬럼 추가
  src/main/java/com/dnd/runus/domain/level/Level.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/level/entity/LevelEntity.java
  src/main/resources/db/migration/V5.0.0__add_level_image.sql
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImplTest.java
Labels: feature

#74 Refactor: apple oidc provider를 단순화하도록 수정
  src/main/java/com/dnd/runus/application/oauth/OauthService.java
  src/main/java/com/dnd/runus/auth/oidc/client/AppleAuthClient.java
  src/main/java/com/dnd/runus/auth/oidc/client/RestClientConfig.java
  src/main/java/com/dnd/runus/auth/oidc/provider/JwtParser.java
  src/main/java/com/dnd/runus/auth/oidc/provider/OidcProvider.java
  src/main/java/com/dnd/runus/auth/oidc/provider/OidcProviderRegistry.java
  src/main/java/com/dnd/runus/auth/oidc/provider/PublicKeyProvider.java
  src/main/java/com/dnd/runus/auth/oidc/provider/apple/AppleOidcProvider.java
  src/main/java/com/dnd/runus/auth/oidc/provider/apple/dto/AppleAuthRevokeRequest.java
  src/main/java/com/dnd/runus/auth/oidc/provider/apple/dto/AppleAuthTokenRequest.java
  src/main/java/com/dnd/runus/auth/oidc/provider/apple/dto/AppleAuthTokenResponse.java
  src/main/java/com/dnd/runus/auth/oidc/provider/impl/AppleAuthProvider.java
  src/main/java/com/dnd/runus/auth/oidc/vo/OidcPublicKeys.java
  src/main/java/com/dnd/runus/client/vo/AppleAuthRevokeRequest.java
  src/main/java/com/dnd/runus/client/vo/AppleAuthTokenRequest.java
  src/main/java/com/dnd/runus/client/vo/OidcPublicKey.java
  src/main/java/com/dnd/runus/client/vo/OidcPublicKeyList.java
  src/main/java/com/dnd/runus/client/web/AppleAuthClient.java
  src/main/java/com/dnd/runus/client/web/AppleAuthClientComponent.java
  src/main/java/com/dnd/runus/domain/badge/BadgeAchievement.java
  src/main/java/com/dnd/runus/domain/badge/BadgeAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeAchievementEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeEntity.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/dto/request/OauthRequest.java
  src/main/java/com/dnd/runus/presentation/v1/oauth/dto/request/WithdrawRequest.java
  src/main/resources/application.yml
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/SocialProfileRepositoryImplTest.java
  src/test/resources/application.yml
Labels: refactoring

#81 Feat: member level 현재 경험치 조회 API 추가
  src/main/java/com/dnd/runus/application/member/MemberService.java
  src/main/java/com/dnd/runus/domain/level/Level.java
  src/main/java/com/dnd/runus/domain/member/MemberLevel.java
  src/main/java/com/dnd/runus/domain/member/MemberLevelRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/member/JooqMemberLevelRepository.java
  src/main/java/com/dnd/runus/presentation/v1/member/MemberProfileController.java
  src/main/java/com/dnd/runus/presentation/v1/member/dto/response/MyProfileResponse.java
  src/test/java/com/dnd/runus/application/member/MemberServiceTest.java
Labels: feature

#82 Feat: 사용자 챌린지 기록 저장
  src/main/java/com/dnd/runus/application/challenge/ChallengeService.java
  src/main/java/com/dnd/runus/domain/challenge/Challenge.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeCondition.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeGoalType.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeRepository.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeType.java
  src/main/java/com/dnd/runus/domain/challenge/ComparisonType.java
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievement.java
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementRecord.java
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementRepository.java
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengePercentageValues.java
  src/main/java/com/dnd/runus/global/constant/ChallengeGoalType.java
  src/main/java/com/dnd/runus/global/constant/ChallengeResultComment.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeAchievementRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeAchievementEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeData.java
  src/main/java/com/dnd/runus/presentation/v1/challenge/dto/response/ChallengeAchievementResponse.java
  src/main/resources/db/migration/V5.0.2__create_challenge_achievement_table.sql
  src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java
  src/test/java/com/dnd/runus/domain/challenge/ChallengeTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeRepositoryImplTest.java
Labels: feature

#91 Feat: running 조회 API 추가
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/domain/running/RunningRecord.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/RunningRecordMetricsDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordRequest.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlyDatesResponse.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSummaryResponse.java
  src/main/resources/db/migration/V5.0.3__running_record_add_end_location.sql
  src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
  src/test/java/com/dnd/runus/domain/challenge/ChallengeTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntityTest.java
Labels: feature

#97 Fix : 챌린지 성취 관련 수정
  src/main/java/com/dnd/runus/application/challenge/ChallengeService.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeCondition.java
  src/main/java/com/dnd/runus/domain/challenge/GoalType.java
  src/main/java/com/dnd/runus/domain/challenge/achievement/dto/ChallengeAchievementDto.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeData.java
  src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java
  src/test/java/com/dnd/runus/domain/challenge/ChallengeTest.java
Labels: feature

#107 Fix: challenge 반환 dto에서 id가 아닌 챌린지 정보도 반환하도록 수정
  src/main/java/com/dnd/runus/application/challenge/ChallengeService.java
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/domain/challenge/Challenge.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeCondition.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeRepository.java
  src/main/java/com/dnd/runus/domain/challenge/ChallengeWithCondition.java
  src/main/java/com/dnd/runus/domain/challenge/GoalMetricType.java
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievement.java
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementRepository.java
  src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievement.java
  src/main/java/com/dnd/runus/domain/goalAchievement/dto/GoalAchievementDto.java
  src/main/java/com/dnd/runus/domain/goalAchievement/dto/GoalAchievementSaveDto.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/challenge/JooqChallengeRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeAchievementEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeGoalConditionEntity.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jpa/goalAchievement/entity/GoalAchievementEntity.java
  src/main/java/com/dnd/runus/presentation/v1/challenge/dto/response/ChallengesResponse.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/ChallengeDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/RunningRecordMetricsDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningAchievementMode.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordRequest.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
  src/test/java/com/dnd/runus/domain/challenge/ChallengeWithConditionTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/goalAchievement/GoalAchievementRepositoryImplTest.java
Labels: feature

#108 Feat: weather client 추가
  src/main/java/com/dnd/runus/global/constant/WeatherType.java
  src/main/java/com/dnd/runus/infrastructure/weather/WeatherClient.java
  src/main/java/com/dnd/runus/infrastructure/weather/WeatherInfo.java
  src/main/java/com/dnd/runus/infrastructure/weather/mock/MockWeatherClient.java
Labels: feature

#109 Feat: 이번 달 러닝 기록 조회 구현
  src/main/java/com/dnd/runus/application/running/RunningRecordService.java
  src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
  src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlySummaryResponse.java
  src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
Labels: feature

#110 Fix: running record 저장시 challenge sub title 정보도 반환하도록 변경
  src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievement.java
  src/main/java/com/dnd/runus/global/constant/RunningResultComment.java
  src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/ChallengeDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
Labels: feature

#114 Fix: 이번달 달린 거리 조회시 null 처리 관련 수정
  src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java
  src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
Labels: bug

#112 Feat: running record 저장시 목표 성취 정보를 같이 반환하도록 수정
  src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievement.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/GoalResultDto.java
  src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
Labels: feature

#117 Feat: weather 조회 api 추가
  src/main/java/com/dnd/runus/application/weather/WeatherService.java
  src/main/java/com/dnd/runus/global/constant/WeatherType.java
  src/main/java/com/dnd/runus/presentation/v1/weather/WeatherController.java
  src/main/java/com/dnd/runus/presentation/v1/weather/dto/WeatherResponse.java
Labels: feature
